tournois/pages/urls.py
from django.urls import path
from django.urls import include

from . import views

app_name = 'tournois'

urlpatterns = [
    path('', views.tournois, name='tournois'),
    path('<int:tournoi_id>/', views.tournoi, name = 'tournoi'),
    path('poule/<int:poule_id>/', views.poule, name = 'poule'),
    path('match/<int:match_id>/', views.match, name = 'match'),
    path('register/', views.register, name='register'),
    path('account/login/', views.login, name='login'),
    path('account/logout/', views.logout, name='logout'),
    
    # path('comment/<int:match_id>',views.match, name='comment'),
]

tournois/tournois/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tournois/', include('pages.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

tournois/pages/models.py
from datetime import date, timezone
from django.db import models
from django.utils import timezone


class Tournoi(models.Model):
    name = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    date_start = models.DateField(null=True)
    date_end = models.DateField(null=True)
    
    def __str__(self):
        return self.name
    
class Poule(models.Model):

    number = models.CharField(max_length=20,default=0)
    tournoi = models.ForeignKey('Tournoi',on_delete=models.CASCADE)
    equipes = models.ManyToManyField('Equipe')
    
    def __str__(self):
        return self.tournoi.name+', poule'+self.number
    
    def points(self):
        point = {}
        scored = {}
        conceded = {}
        for match in Match.objects.filter(poule=self):
            if match.score1 > match.score2:   #equipe1 wins
                scored[match.equipe1.id] = scored.get(match.equipe1.id, 0) + match.score1  
                conceded[match.equipe1.id] = conceded.get(match.equipe1.id, 0) + match.score2
                scored[match.equipe2.id] = scored.get(match.equipe2.id, 0) + match.score2
                conceded[match.equipe2.id] = conceded.get(match.equipe2.id, 0) + match.score1
                point[match.equipe1.id] = point.get(match.equipe1.id, 0) + 3
                point[match.equipe2.id] = point.get(match.equipe2.id, 0) + 0
            elif match.score1 == match.score2:
                scored[match.equipe1.id] = scored.get(match.equipe1.id, 0) + match.score1
                conceded[match.equipe1.id] = conceded.get(match.equipe1.id, 0) + match.score2
                scored[match.equipe2.id] = scored.get(match.equipe2.id, 0) + match.score2
                conceded[match.equipe2.id] = conceded.get(match.equipe2.id, 0) + match.score1
                point[match.equipe1.id] = point.get(match.equipe1.id, 0) + 1
                point[match.equipe2.id] = point.get(match.equipe2.id, 0) + 1
            elif match.score1 < match.score2: #equipe1 loses
                scored[match.equipe1.id] = scored.get(match.equipe1.id, 0) + match.score1
                conceded[match.equipe1.id] = conceded.get(match.equipe1.id, 0) + match.score2
                scored[match.equipe2.id] = scored.get(match.equipe2.id, 0) + match.score2
                conceded[match.equipe2.id] = conceded.get(match.equipe2.id, 0) + match.score1
                point[match.equipe2.id] = point.get(match.equipe2.id, 0) + 3
                point[match.equipe1.id] = point.get(match.equipe1.id, 0) + 0
        # make a rank of teams first by points and second by recorded, third by conceded
        length = len(point)
        points = {} 
        for i in range(length):
            k_n = [(k,v) for k,v in point.items()][0][0] # key to compare
            for k,v in point.items():
                if v > point.get(k_n):
                    k_n = k 
                elif v == point.get(k_n):
                    if scored.get(k) > scored.get(k_n):
                        k_n = k
                    elif  scored.get(k) == scored.get(k_n):
                        if conceded.get(k) < conceded.get(k):
                            k_n = k
            points[Equipe.objects.get(pk=k_n).name] = [point.get(k_n), scored.get(k_n), conceded.get(k_n)]
            point.pop(k_n)
        return points
            
class Match(models.Model):
    time = models.DateTimeField(null=True)
    location = models.CharField(max_length=200)
    score1 = models.IntegerField(default=0)
    score2 = models.IntegerField(default=0)
    equipe1 = models.ForeignKey('Equipe',on_delete=models.CASCADE,related_name='equipe01',null=True)
    equipe2 = models.ForeignKey('Equipe',on_delete=models.CASCADE,related_name='equipe02',null=True)
    poule = models.ForeignKey('Poule',on_delete=models.CASCADE,null=True)
    
    
    def __str__(self):
        return self.equipe1.name+" vs "+self.equipe2.name
    
class Equipe(models.Model):
    name = models.CharField(max_length=200)
    coach_name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name
      
class Player(models.Model):
    name = models.CharField(max_length=200)
    equipe = models.ForeignKey('Equipe',on_delete=models.CASCADE,null=True)
    
    def __str__(self):
        return self.name
    
class Comment(models.Model):
    match = models.ForeignKey('Match',on_delete=models.CASCADE,null=True)
    body = models.CharField(max_length=500,null=True)
    time = models.DateTimeField(auto_now_add=True)
    user = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.body[:20]

    
    
    
    
    

tournois/pages/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    model = Comment
    fields = ['body','user']
    

tournois/disks/views.py
from django.shortcuts import render,get_list_or_404,get_object_or_404
from django.http import HttpResponse

from .models import Tournoi
from .models import Poule

def tournoi(request):
    tournois = get_list_or_404(Tournoi)
    return render(request,'tournois/tournoi.html',{'tournois':tournois})

def poules(request,tournoi_id):
    tournoi = get_object_or_404(Tournoi, pk=tournoi_id)
    return render(request,'tournois/poule.html',{'tournoi':tournoi})

def matches(request,tournoi_id,poule_id):
    poule = get_object_or_404(Poule, pk=poule_id)
    points = poule.points()
    return render(request,'tournois/match.html',{'poule':poule,'points':points})
    

tournois/pages/views.py
from django.shortcuts import render,get_list_or_404,get_object_or_404,redirect
from django.contrib.auth import authenticate
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate

from .forms import CommentForm

from .models import Tournoi
from .models import Poule
from .models import Match


import hashlib

def tournois(request):
    tournois = get_list_or_404(Tournoi)
    
    return render(request,'tournois/tournois.html',{'tournois':tournois})

def tournoi(request, tournoi_id):
    tournoi = get_object_or_404(Tournoi, pk=tournoi_id)
    
    return render(request,'tournois/tournoi.html',{'tournoi':tournoi})

def poule(request, poule_id):
    poule = get_object_or_404(Poule, pk=poule_id)
    points = poule.points()
    
    return render(request,'tournois/poule.html',{'poule':poule,'points':points})

def match(request, match_id):
    match = get_object_or_404(Match, pk=match_id)
    
    return render(request,'tournois/match.html',{'match':match})



 
def register(request):
    pass
    
    return render(request,"tournois/register.html")

def login(request):

    # next = request.GET.get('next', '')

    # if request.method == 'POST':
    #     form = LoginForm(request.POST)
    #     if form.is_valid():
    #         username = form.cleaned_data['username']
    #         password = form.cleaned_data['password']

    #         user = auth.authenticate(username=username, password=password)

    #         if user is not None and user.is_active:
    #             auth.login(request, user)
    #             if  next == "":
    #                 return HttpResponseRedirect(reverse('tournois:tournois', args=[user.id]))
    #             else:
    #                 return HttpResponseRedirect(next)

    #         else:
                
    #            return render(request, 'login', {'form': form,})
    # else:
    #     form = LoginForm()
    pass

    return render(request, 'tournois/tournois.html')

def logout(request):

    pass
    return redirect('/tournois/')

    

tournois/disks/templates/disks/poules.html
{% if tournoi %}
    <h2> {{tournoi.name}} </h2>
    <h3> by {{tournoi.place}} </h3>
    <table border="1">
        <tr>
            <td>Number</td>
        </tr>
        {% for poule in tournoi.poule_set.all %}
            <tr>
                <td>{{poule.number}}</td>
            </tr>
        {% endfor %}
        </table>
{% endif %}

<a href="{% url 'disks:tournois' %}"> Back to tournois list </a>

tournois/disks/templates/disks/tournois.html
{% if tournois %}
    <h2> The list of tournois </h2>
    <table border="1">
        <tr>
            <td style="text-align:center;"> name </td>
            <td style="text-align:center;"> place </td>
        <tr>
        {% for tournoi in tournois %}
            <tr>
                <td> <a href="{% url 'disks:poules' tournoi.id %}"> {{tournoi.name}} </a></td>
                <td> {{tournoi.place}}<td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <h1> No tournoi available.</h1>
{% endif %}

tournois/disks/templates/tournois/poules.html
{% if tournoi %}
    <h2> {{tournoi.name}} </h2>
    <h3> by {{tournoi.place}} </h3>
    <table border="1">
        <tr>
            <td>Number</td>
        </tr>
        {% for poule in tournoi.poule_set.all %}
            <tr>
                <td><a href="{% url 'tournois:matches' poule.tournoi.id poule.id %}"> {{tournoi.name}}, Poule {{poule.id}}</a></td>
            </tr>
        {% endfor %}
        </table>
{% endif %}

<a href="{% url 'tournois:tournois' %}"> Back to tournois list </a>

tournois/disks/templates/tournois/tournois.html
{% if tournois %}
    <h2> The list of tournois </h2>
    <table border="1">
        <tr>
            <td style="text-align:center;"> name </td>
            <td style="text-align:center;"> place </td>
            <td style="text-align:center;"> time </td>
        <tr>
        {% for tournoi in tournois %}
            <tr>
                <td> <a href="{% url 'tournois:poules' tournoi.id %}"> {{tournoi.name}} </a></td>
                <td> {{tournoi.place}}</td>
                <td> Date: from {{tournoi.date_start}} to {{tournoi.date_end}} </td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <h1> No tournoi available.</h1>
{% endif %}

tournois/pages/templates/tournois/match.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% comment %}
Extend site-wide base HTML template located in main templates/ dir
(same level as manage.py)
{% endcomment %}

{% block title %}match{% endblock title %}

{% block content %}
{% if match %}
    <h3> {{match.poule.tournoi}}, Poule{{match.poule.number}} </h3>
    <h4> by {{match.poule.tournoi.location}} </h4>
    <hr>

    <nav class="navbar navbar-expand-sm bg-light navbar-light">
        <div class="container-fluid">
        <ul class="navbar-nav">
            <li class="nav-item">
            <a class="nav-link active" href="{% url 'tournois:tournois' %}">Home</a>
            </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'tournois:tournoi' match.poule.tournoi.id%}">{{match.poule.tournoi.name}}</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'tournois:poule' match.poule.id%}">Poule{{match.poule.id}}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'tournois:match' match.id%}">{{match.equipe1}} VS {{match.equipe2}}</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
               
                <a class="nav-link disabled" href="#">{{request.user.username}}</a>
                
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout'%}">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login'%}">Login</a>
            </li>
        {% endif %} 
        </ul>

        </div>
    </nav>
    <hr>
    <div class="card bg-light text-dark">
        <div class="card-body">
        <h5 class="text-primary" class="card-title">{{match.score1}} {{match.equipe1}} vs {{match.equipe2}} {{match.score2}}</h5>
        <h6 class="card-text">{{match.location}}</h6>
        <h6 class="card-text">{{match.time.date}}</h6>
        </div>
    </div>
    <hr>

    {% if request.user.is_authenticated %}

    <form action="tournois:match">
        <div class="mb-3 mt-3">
          <label for="comment">Add a Comment:</label>
          <textarea class="form-control" rows="5" id="comment" name="comment"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    {% else %}
    <div class="card bg-light text-dark">
        <div class="card-body">
        <h6> Add Comments </h6>
        <p> Please <a href="{% url 'login' %}?next={{ request.path }}">login</a> to comment this match </p>
        </div>
    </div>
    {% endif %}
    <hr>
    <h6>Comments</h6>
    {% for comment in match.comment_set.all %}
    <div class="card bg-light text-dark">
        <div class="card-body">
        <p class="text-primary" class="card-title">user: {{comment.user}}  {{comment.time}}</p>
        <p class="card-text">{{comment.body}}</p>
        </div>
    </div>
    {% endfor %}


{% endif %}
{% endblock content %}

tournois/pages/templates/tournois/poule.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% comment %}
Extend site-wide base HTML template located in main templates/ dir
(same level as manage.py)
{% endcomment %}

{% block title %}poule{% endblock title %}

{% block content %}

{% if poule%}
    <h3> {{poule.tournoi}}, Poule{{poule.number}} </h3>
    <h4> by {{poule.tournoi.location}} </h4>
    <hr>
    <nav class="navbar navbar-expand-sm bg-light navbar-light">
        <div class="container-fluid">
        <ul class="navbar-nav">
            <li class="nav-item">
            <a class="nav-link active" href="{% url 'tournois:tournois' %}">Home</a>
            </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'tournois:tournoi' poule.tournoi.id%}">{{poule.tournoi.name}}</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'tournois:poule' poule.id%}">Poule{{poule.id}}</a>
            </li>
            <li class="nav-item">
            <a class="nav-link disabled" href="#">Match</a>
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                   
                    <a class="nav-link disabled" href="#">{{request.user.username}}</a>
                    
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout'%}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login'%}">Login</a>
                </li>
            {% endif %} 
        </ul>
        </div>
    </nav>
<hr>

<div class="card bg-light text-dark">
    <div class="card-body">
        <h5> Teams </h5>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th> Team name </th>
                    <th> Pool points </th>
                    <th> Scored </th>
                    <th> Conceded </th>
                </tr>
            </thead>
            <tbody>
                {% for id,point in points.items %}
                <tr>
                    <td> {{id}}</td>
                    <td> {{point.0}}</td>
                    <td> {{point.1}}</td>
                    <td> {{point.2}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
         <h5> Matches </h5>
         {% for match in poule.match_set.all%}
         <div class="card">
            <div class="card-body">
            <h6 class="text-primary" class="card-title">
                <a href="{% url 'tournois:match' match.id %}">
                    {{match.score1}} {{match.equipe1}} vs {{match.equipe2}} {{match.score2}}</a></h6>
            <p class="card-text">{{match.location}}, {{match.time.date}}</p>
            </div>
        </div>
        {% endfor %}
        </div>
    </div>
{% else %}
<h1> No match available.</h1>
{% endif %}

{% endblock content %}

tournois/pages/templates/tournois/tournoi.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% comment %}
Extend site-wide base HTML template located in main templates/ dir
(same level as manage.py)
{% endcomment %}

{% block title %}poule{% endblock title %}

{% block content %}

{% if tournoi %}
    <h3> {{tournoi.name}} </h3>
    <h4> by {{tournoi.location}} </h4>
    <hr>
    <nav class="navbar navbar-expand-sm bg-light navbar-light">
        <div class="container-fluid">
        <ul class="navbar-nav">
            <li class="nav-item">
            <a class="nav-link active" href="{% url 'tournois:tournois' %}">Home</a>
            </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'tournois:tournoi' tournoi.id%}">{{tournoi.name}}</a>
            <li class="nav-item">
            <a class="nav-link disabled" href="#">Poule</a>
            </li>
            <li class="nav-item">
            <a class="nav-link disabled" href="#">Match</a>
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                   
                    <a class="nav-link disabled" href="#">{{request.user.username}}</a>
                    
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout'%}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login'%}">Login</a>
                </li>
            {% endif %} 
        </ul>
        </div>
    </nav>
    <hr>
    <div class="card bg-light text-dark">
        <div class="card-body">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th> Number</th>
                    <th> Les Équipes </th>
                </tr>
            </thead>
            <tbody>
                {% for poule in tournoi.poule_set.all %}
                    <tr>
                        <td><a href="{% url 'tournois:poule' poule.id %}"> {{tournoi.name}}, Poule {{poule.id}}</a></td>
                        <td>
                            {% for equipe in poule.equipes.all %}
                                 {{equipe.name}}, 
                             {% endfor %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
{% endif %}

{% endblock content %}

tournois/pages/templates/tournois/tournois.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% comment %}
Extend site-wide base HTML template located in main templates/ dir
(same level as manage.py)
{% endcomment %}

{% block title %}tournoi{% endblock title %}

{% block content %}


{% if tournois %}
    <div class="container mt-3">
    <h3> The list of tournois </h3>
    <hr>
    <nav class="navbar navbar-expand-sm bg-light navbar-light">
        <div class="container-fluid">
        <ul class="navbar-nav">
            <li class="nav-item">
            <a class="nav-link active" href="{% url 'tournois:tournois' %}">Home</a>
            </li>
            <li class="nav-item">
            <a class="nav-link disabled" href="#">Tournoi</a>
            </li>
            <li class="nav-item">
            <a class="nav-link disabled" href="#">Poule</a>
            </li>
            <li class="nav-item">
            <a class="nav-link disabled" href="#">Match</a>
            </li>
            
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                   
                    <a class="nav-link disabled" href="#">{{request.user.username}}</a>
                    
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout'%}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login'%}">Login</a>
                </li>
            {% endif %} 
        </ul>
        </div>
    </nav>
    <hr>

    <div class="card bg-light text-dark">
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th> Name </th>
                            <th> Place </th>
                            <th> From </th>
                            <th> To </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for tournoi in tournois %}
                            <tr>
                                <td> <a href="{% url 'tournois:tournoi' tournoi.id %}"> {{tournoi.name}} </a></td>
                                <td> {{tournoi.location}}</td>
                                <td> {{tournoi.date_start}} </td>
                                <td> {{tournoi.date_end}} </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
    </div>

{% else %}
    <h1> No tournoi available.</h1>
{% endif %}

{% endblock content %}

tournois/templates/base.html
{% load static %}

{# Load the tag library #}
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Tournois{% endblock %}</title>

    {# Load Bootstrap CSS #}
    {% bootstrap_css %}

    {% block css %}{% endblock %}
</head>

<body>
    
    <div class="container">
        <div class="row pb-3">
            <header>
                <img src="{% static 'images/champion.png' %}" width=25px alt="logo"/>
                Gestion des tournois avec des poules<br>
                <div align=center>
                <img src="{% static 'images/pngegg.png' %}" width=480px alt="logo"/>
                </div>
            </header>
        </div>
        

        {% block content %}{% endblock %}

        <div class="row pt-5">
            <footer>
                <em>&copy; ISAE-SUPAERO</em>
            </footer>
        </div>
    </div>
    {# Load Bootstrap Javascript #}
    {% bootstrap_javascript %}
</body>
</html> 